export type BreedSize = "tiny" | "small" | "medium" | "large" | "giant";

export type Breed = {
  id: string;
  nameJa: string;
  nameEn: string;
  size: BreedSize;
  weightMin: number;
  weightMax: number;
  chestAvg: number;
  backAvg: number;
  neckAvg: number;
  popular?: boolean;
};

export const breeds: Breed[] = [
  // 小型 (tiny / small)
  {
    id: "chihuahua",
    nameJa: "チワワ",
    nameEn: "Chihuahua",
    size: "tiny",
    weightMin: 1.5,
    weightMax: 3,
    chestAvg: 30,
    backAvg: 22,
    neckAvg: 19,
    popular: true,
  },
  {
    id: "toy-poodle",
    nameJa: "トイプードル",
    nameEn: "Toy Poodle",
    size: "small",
    weightMin: 3,
    weightMax: 5,
    chestAvg: 38,
    backAvg: 28,
    neckAvg: 24,
    popular: true,
  },
  {
    id: "pomeranian",
    nameJa: "ポメラニアン",
    nameEn: "Pomeranian",
    size: "tiny",
    weightMin: 1.5,
    weightMax: 3.5,
    chestAvg: 33,
    backAvg: 24,
    neckAvg: 21,
    popular: true,
  },
  {
    id: "shih-tzu",
    nameJa: "シーズー",
    nameEn: "Shih Tzu",
    size: "small",
    weightMin: 4,
    weightMax: 7,
    chestAvg: 42,
    backAvg: 30,
    neckAvg: 27,
  },
  {
    id: "maltese",
    nameJa: "マルチーズ",
    nameEn: "Maltese",
    size: "tiny",
    weightMin: 2,
    weightMax: 3.5,
    chestAvg: 32,
    backAvg: 23,
    neckAvg: 20,
  },
  {
    id: "yorkie",
    nameJa: "ヨークシャテリア",
    nameEn: "Yorkshire Terrier",
    size: "tiny",
    weightMin: 2,
    weightMax: 3.5,
    chestAvg: 31,
    backAvg: 22,
    neckAvg: 20,
  },
  {
    id: "dachshund",
    nameJa: "ダックスフンド",
    nameEn: "Dachshund",
    size: "small",
    weightMin: 4,
    weightMax: 9,
    chestAvg: 45,
    backAvg: 36,
    neckAvg: 28,
    popular: true,
  },
  {
    id: "french-bulldog",
    nameJa: "フレンチブルドッグ",
    nameEn: "French Bulldog",
    size: "small",
    weightMin: 8,
    weightMax: 14,
    chestAvg: 52,
    backAvg: 32,
    neckAvg: 36,
    popular: true,
  },
  {
    id: "papillon",
    nameJa: "パピヨン",
    nameEn: "Papillon",
    size: "small",
    weightMin: 3,
    weightMax: 5,
    chestAvg: 36,
    backAvg: 26,
    neckAvg: 22,
  },
  {
    id: "jack-russell",
    nameJa: "ジャックラッセル",
    nameEn: "Jack Russell Terrier",
    size: "small",
    weightMin: 5,
    weightMax: 8,
    chestAvg: 42,
    backAvg: 30,
    neckAvg: 28,
  },
  {
    id: "pug",
    nameJa: "パグ",
    nameEn: "Pug",
    size: "small",
    weightMin: 6,
    weightMax: 9,
    chestAvg: 50,
    backAvg: 30,
    neckAvg: 34,
    popular: true,
  },
  {
    id: "miniature-schnauzer",
    nameJa: "ミニチュアシュナウザー",
    nameEn: "Miniature Schnauzer",
    size: "small",
    weightMin: 5,
    weightMax: 9,
    chestAvg: 46,
    backAvg: 32,
    neckAvg: 30,
    popular: true,
  },
  {
    id: "cavalier",
    nameJa: "キャバリア",
    nameEn: "Cavalier King Charles Spaniel",
    size: "small",
    weightMin: 6,
    weightMax: 8,
    chestAvg: 44,
    backAvg: 32,
    neckAvg: 30,
  },
  {
    id: "bichon-frise",
    nameJa: "ビションフリーゼ",
    nameEn: "Bichon Frise",
    size: "small",
    weightMin: 5,
    weightMax: 7,
    chestAvg: 42,
    backAvg: 30,
    neckAvg: 28,
  },
  {
    id: "boston-terrier",
    nameJa: "ボストンテリア",
    nameEn: "Boston Terrier",
    size: "small",
    weightMin: 5,
    weightMax: 11,
    chestAvg: 48,
    backAvg: 34,
    neckAvg: 32,
  },
  {
    id: "miniature-pinscher",
    nameJa: "ミニチュアピンシャー",
    nameEn: "Miniature Pinscher",
    size: "tiny",
    weightMin: 4,
    weightMax: 5,
    chestAvg: 36,
    backAvg: 28,
    neckAvg: 24,
  },
  {
    id: "italian-greyhound",
    nameJa: "イタリアングレーハウンド",
    nameEn: "Italian Greyhound",
    size: "small",
    weightMin: 3,
    weightMax: 5,
    chestAvg: 38,
    backAvg: 30,
    neckAvg: 24,
  },
  {
    id: "pekingese",
    nameJa: "ペキニーズ",
    nameEn: "Pekingese",
    size: "small",
    weightMin: 3,
    weightMax: 6,
    chestAvg: 44,
    backAvg: 28,
    neckAvg: 30,
  },
  {
    id: "lhasa-apso",
    nameJa: "ラサアプソ",
    nameEn: "Lhasa Apso",
    size: "small",
    weightMin: 5,
    weightMax: 8,
    chestAvg: 44,
    backAvg: 32,
    neckAvg: 28,
  },
  {
    id: "japanese-spitz",
    nameJa: "日本スピッツ",
    nameEn: "Japanese Spitz",
    size: "small",
    weightMin: 5,
    weightMax: 11,
    chestAvg: 48,
    backAvg: 34,
    neckAvg: 32,
  },
  {
    id: "cairn-terrier",
    nameJa: "ケアーンテリア",
    nameEn: "Cairn Terrier",
    size: "small",
    weightMin: 6,
    weightMax: 8,
    chestAvg: 42,
    backAvg: 30,
    neckAvg: 28,
  },
  {
    id: "west-highland",
    nameJa: "ウエストハイランドホワイトテリア",
    nameEn: "West Highland White Terrier",
    size: "small",
    weightMin: 7,
    weightMax: 10,
    chestAvg: 44,
    backAvg: 32,
    neckAvg: 30,
  },
  {
    id: "cocker-spaniel",
    nameJa: "コッカースパニエル",
    nameEn: "Cocker Spaniel",
    size: "medium",
    weightMin: 11,
    weightMax: 14,
    chestAvg: 56,
    backAvg: 38,
    neckAvg: 36,
  },
  {
    id: "schnauzer-standard",
    nameJa: "スタンダードシュナウザー",
    nameEn: "Standard Schnauzer",
    size: "medium",
    weightMin: 14,
    weightMax: 23,
    chestAvg: 64,
    backAvg: 46,
    neckAvg: 40,
  },
  // 中型 (medium)
  {
    id: "shiba",
    nameJa: "柴犬",
    nameEn: "Shiba Inu",
    size: "medium",
    weightMin: 8,
    weightMax: 12,
    chestAvg: 55,
    backAvg: 42,
    neckAvg: 34,
    popular: true,
  },
  {
    id: "corgi",
    nameJa: "コーギー",
    nameEn: "Welsh Corgi",
    size: "medium",
    weightMin: 10,
    weightMax: 14,
    chestAvg: 58,
    backAvg: 38,
    neckAvg: 36,
    popular: true,
  },
  {
    id: "beagle",
    nameJa: "ビーグル",
    nameEn: "Beagle",
    size: "medium",
    weightMin: 9,
    weightMax: 13,
    chestAvg: 56,
    backAvg: 40,
    neckAvg: 35,
  },
  {
    id: "border-collie",
    nameJa: "ボーダーコリー",
    nameEn: "Border Collie",
    size: "medium",
    weightMin: 14,
    weightMax: 20,
    chestAvg: 64,
    backAvg: 48,
    neckAvg: 38,
  },
  {
    id: "sheltie",
    nameJa: "シェルティ",
    nameEn: "Shetland Sheepdog",
    size: "medium",
    weightMin: 7,
    weightMax: 10,
    chestAvg: 52,
    backAvg: 38,
    neckAvg: 34,
  },
  {
    id: "english-bulldog",
    nameJa: "イングリッシュブルドッグ",
    nameEn: "English Bulldog",
    size: "medium",
    weightMin: 18,
    weightMax: 25,
    chestAvg: 70,
    backAvg: 36,
    neckAvg: 46,
  },
  {
    id: "whippet",
    nameJa: "ウィペット",
    nameEn: "Whippet",
    size: "medium",
    weightMin: 9,
    weightMax: 19,
    chestAvg: 58,
    backAvg: 50,
    neckAvg: 36,
  },
  {
    id: "australian-shepherd",
    nameJa: "オーストラリアンシェパード",
    nameEn: "Australian Shepherd",
    size: "medium",
    weightMin: 16,
    weightMax: 32,
    chestAvg: 72,
    backAvg: 50,
    neckAvg: 42,
  },
  {
    id: "vizsla",
    nameJa: "ビズラ",
    nameEn: "Vizsla",
    size: "medium",
    weightMin: 18,
    weightMax: 30,
    chestAvg: 70,
    backAvg: 52,
    neckAvg: 42,
  },
  {
    id: "boxer",
    nameJa: "ボクサー",
    nameEn: "Boxer",
    size: "large",
    weightMin: 25,
    weightMax: 32,
    chestAvg: 76,
    backAvg: 56,
    neckAvg: 48,
  },
  {
    id: "akita",
    nameJa: "秋田犬",
    nameEn: "Akita",
    size: "large",
    weightMin: 32,
    weightMax: 59,
    chestAvg: 88,
    backAvg: 65,
    neckAvg: 56,
    popular: true,
  },
  {
    id: "kai-ken",
    nameJa: "甲斐犬",
    nameEn: "Kai Ken",
    size: "medium",
    weightMin: 11,
    weightMax: 25,
    chestAvg: 60,
    backAvg: 46,
    neckAvg: 38,
  },
  {
    id: "kishu-ken",
    nameJa: "紀州犬",
    nameEn: "Kishu Ken",
    size: "medium",
    weightMin: 14,
    weightMax: 27,
    chestAvg: 64,
    backAvg: 48,
    neckAvg: 40,
  },
  {
    id: "hokkaido-ken",
    nameJa: "北海道犬",
    nameEn: "Hokkaido Ken",
    size: "medium",
    weightMin: 20,
    weightMax: 30,
    chestAvg: 66,
    backAvg: 50,
    neckAvg: 40,
  },
  {
    id: "shikoku-ken",
    nameJa: "四国犬",
    nameEn: "Shikoku Ken",
    size: "medium",
    weightMin: 16,
    weightMax: 25,
    chestAvg: 62,
    backAvg: 48,
    neckAvg: 38,
  },
  // 大型 (large / giant)
  {
    id: "golden-retriever",
    nameJa: "ゴールデンレトリバー",
    nameEn: "Golden Retriever",
    size: "large",
    weightMin: 25,
    weightMax: 34,
    chestAvg: 78,
    backAvg: 60,
    neckAvg: 48,
    popular: true,
  },
  {
    id: "labrador",
    nameJa: "ラブラドールレトリバー",
    nameEn: "Labrador Retriever",
    size: "large",
    weightMin: 25,
    weightMax: 36,
    chestAvg: 80,
    backAvg: 60,
    neckAvg: 50,
    popular: true,
  },
  {
    id: "husky",
    nameJa: "シベリアンハスキー",
    nameEn: "Siberian Husky",
    size: "large",
    weightMin: 20,
    weightMax: 28,
    chestAvg: 76,
    backAvg: 60,
    neckAvg: 46,
  },
  {
    id: "german-shepherd",
    nameJa: "ジャーマンシェパード",
    nameEn: "German Shepherd",
    size: "large",
    weightMin: 28,
    weightMax: 40,
    chestAvg: 84,
    backAvg: 65,
    neckAvg: 52,
  },
  {
    id: "doberman",
    nameJa: "ドーベルマン",
    nameEn: "Doberman Pinscher",
    size: "large",
    weightMin: 27,
    weightMax: 45,
    chestAvg: 86,
    backAvg: 65,
    neckAvg: 52,
  },
  {
    id: "rottweiler",
    nameJa: "ロットワイラー",
    nameEn: "Rottweiler",
    size: "large",
    weightMin: 35,
    weightMax: 60,
    chestAvg: 92,
    backAvg: 60,
    neckAvg: 56,
  },
  {
    id: "standard-poodle",
    nameJa: "スタンダードプードル",
    nameEn: "Standard Poodle",
    size: "large",
    weightMin: 20,
    weightMax: 32,
    chestAvg: 78,
    backAvg: 56,
    neckAvg: 46,
  },
  {
    id: "samoyed",
    nameJa: "サモエド",
    nameEn: "Samoyed",
    size: "large",
    weightMin: 16,
    weightMax: 30,
    chestAvg: 76,
    backAvg: 56,
    neckAvg: 46,
  },
  {
    id: "bernese",
    nameJa: "バーニーズマウンテンドッグ",
    nameEn: "Bernese Mountain Dog",
    size: "giant",
    weightMin: 35,
    weightMax: 50,
    chestAvg: 92,
    backAvg: 66,
    neckAvg: 56,
    popular: true,
  },
  {
    id: "alaskan-malamute",
    nameJa: "アラスカンマラミュート",
    nameEn: "Alaskan Malamute",
    size: "giant",
    weightMin: 32,
    weightMax: 43,
    chestAvg: 88,
    backAvg: 66,
    neckAvg: 54,
  },
  {
    id: "great-dane",
    nameJa: "グレートデーン",
    nameEn: "Great Dane",
    size: "giant",
    weightMin: 50,
    weightMax: 80,
    chestAvg: 100,
    backAvg: 78,
    neckAvg: 60,
  },
  {
    id: "saint-bernard",
    nameJa: "セントバーナード",
    nameEn: "Saint Bernard",
    size: "giant",
    weightMin: 65,
    weightMax: 90,
    chestAvg: 104,
    backAvg: 70,
    neckAvg: 64,
  },
  {
    id: "great-pyrenees",
    nameJa: "グレートピレニーズ",
    nameEn: "Great Pyrenees",
    size: "giant",
    weightMin: 38,
    weightMax: 60,
    chestAvg: 96,
    backAvg: 70,
    neckAvg: 58,
  },
  {
    id: "newfoundland",
    nameJa: "ニューファンドランド",
    nameEn: "Newfoundland",
    size: "giant",
    weightMin: 45,
    weightMax: 70,
    chestAvg: 100,
    backAvg: 70,
    neckAvg: 60,
  },
  // デザイナーミックス(よく登録される人気MIX)
  {
    id: "labradoodle",
    nameJa: "ラブラドゥードル",
    nameEn: "Labradoodle",
    size: "large",
    weightMin: 22,
    weightMax: 32,
    chestAvg: 76,
    backAvg: 56,
    neckAvg: 46,
    popular: true,
  },
  {
    id: "goldendoodle",
    nameJa: "ゴールデンドゥードル",
    nameEn: "Goldendoodle",
    size: "large",
    weightMin: 20,
    weightMax: 32,
    chestAvg: 76,
    backAvg: 56,
    neckAvg: 46,
  },
  {
    id: "cockapoo",
    nameJa: "コッカプー",
    nameEn: "Cockapoo",
    size: "small",
    weightMin: 5,
    weightMax: 12,
    chestAvg: 48,
    backAvg: 34,
    neckAvg: 32,
  },
  {
    id: "maltipoo",
    nameJa: "マルプー",
    nameEn: "Maltipoo",
    size: "small",
    weightMin: 3,
    weightMax: 6,
    chestAvg: 36,
    backAvg: 26,
    neckAvg: 24,
    popular: true,
  },
  {
    id: "chiwawa-poodle",
    nameJa: "チワプー",
    nameEn: "Chi-poo",
    size: "tiny",
    weightMin: 2,
    weightMax: 5,
    chestAvg: 32,
    backAvg: 24,
    neckAvg: 22,
  },
  {
    id: "pomchi",
    nameJa: "ポメチワワ",
    nameEn: "Pomchi",
    size: "tiny",
    weightMin: 2,
    weightMax: 5,
    chestAvg: 32,
    backAvg: 24,
    neckAvg: 21,
  },
  // mix扱い
  {
    id: "mix",
    nameJa: "ミックス犬(親犬種を選択)",
    nameEn: "Mixed breed (pick parents)",
    size: "small",
    weightMin: 0,
    weightMax: 0,
    chestAvg: 0,
    backAvg: 0,
    neckAvg: 0,
  },
];

export function getBreed(id: string): Breed | undefined {
  return breeds.find((b) => b.id === id);
}

export function getPopularBreeds(): Breed[] {
  return breeds.filter((b) => b.popular);
}

/**
 * 親犬種を2つ受け取って、平均的な採寸値を推定する。
 * MIX犬の場合に使う。
 */
export function estimateMixMeasurements(
  parentA: Breed,
  parentB: Breed,
): { chest: number; back: number; neck: number; weight: number } {
  return {
    chest: Math.round((parentA.chestAvg + parentB.chestAvg) / 2),
    back: Math.round((parentA.backAvg + parentB.backAvg) / 2),
    neck: Math.round((parentA.neckAvg + parentB.neckAvg) / 2),
    weight:
      Math.round(
        ((parentA.weightMin + parentA.weightMax) / 2 +
          (parentB.weightMin + parentB.weightMax) / 2) /
          2 *
          10,
      ) / 10,
  };
}
